### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by walshe** [RafPe/serverless-reqvalidator-plugin#1]
is there a way to get the specific validation errors back in the response, e.g. which fields failed and why etc ?

great plugin!

**Comment by RafPe** [comment]
Hi @walshe Happy that you liked the plugin. Could you describe a bit more situation you are looking into now so I do get a bit more context

**Comment by walshe** [comment]
what I mean is instead of the default response e.g

{
  "message": "Invalid request body"
}

how do I get back the specific issue e.g.:

Request body does not match model schema for content type application/json: [object has missing required properties (["body","subject","to"])]

**Comment by RafPe** [comment]
@walshe something like [this](https://docs.aws.amazon.com/apigateway/latest/developerguide/customize-gateway-responses.html) ??

**Comment by walshe** [comment]
looks complicated

**Comment by RafPe** [comment]
@walshe :) hahahah good one 👍 well I looked at it  - and if you would read through documentation link I sent you you can see that you can do that even via GUI - problem is passing information you want to be displayed.
```
{
  "Type" : "AWS::ApiGateway::GatewayResponse",
  "Properties" : {
    "ResponseParameters" : { String:String, ... },
    "ResponseTemplates" : { String:String, ... },
    "ResponseType" : String,
    "RestApiId" : String,
    "StatusCode" : String
  }
}
```

 In theory we could have plugin to control `GatewayResponse` but I think thats something that community would need to pick up

**Comment by ryanhendry** [comment]
I wanted to get the specific validation errors as well. I figured out you can get them by adding this gateway response block to your serverless.yml
```
resources:
  Resources:
    GatewayResponseBadRequestBody:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        RestApiId: 
          Ref: 'ApiGatewayRestApi'
        ResponseType: BAD_REQUEST_BODY
        ResponseTemplates:
          application/json: "{\"error\":{\"code\":\"your-code-here\", \"message\":$context.error.validationErrorString},\"requestId\":\"$context.requestId\"}"
```
