### ISSUE TITLE
requestHeaders validation

### ISSUE THREAD

**Issue by fstybel** [RafPe/serverless-reqvalidator-plugin#10]
It is possible to validate request headers?

my function:

```yaml
collection:
  handler: src/handlers/collections.handler
  events:
    - http:
        method: post
        path: /some/path
        scopes: [some/scope]
        authorizer:
          arn: arn:aws:cognito-idp:eu-west-1:111111111111:userpool/eu-west-1_xxxxxxx
        documentation:
          requestModels:
            "application/json": myModel
          requestHeaders:
            - name: "x-user-uid"
              description: "User identification"
              required: true
            - name: "Authorization"
              required: true
              description: "Auth Header"
          methodResponses:
            - statusCode: '200'
              responseModels: 
                "application/json": MyModelResponse
            - ${self:custom.commonModelSchemaFragments.MethodResponse400Json}
        reqValidatorName: bodyAndParameters
```

my resource:

```yaml
resources:
  Resources:
    bodyAndParameters:  
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'body-and-parameters'
        RestApiId: 
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
```
