### ISSUE TITLE
Use serverless-reqvalidator-plugin together with serverless-offline

### ISSUE THREAD

**Issue by megaxayda** [RafPe/serverless-reqvalidator-plugin#14]
Would be nice to test reqvalidator on local apigateway using serverless-offline.

**Comment by RafPe** [comment]
@megaxayda could you please post some more info on the subject ?

**Comment by megaxayda** [comment]
When running offline using `serverless offline start`, i want to use req-validator for local api gateway also. It seems to be working only on aws environment.

**Comment by benjefferies** [comment]
This would be awesome. There are a few issues in the serverless offline repo too https://github.com/dherault/serverless-offline/issues/894

**Comment by BartusZak** [comment]
Ah, would love to see that

**Comment by RafPe** [comment]
FYI - At the moment Im swamped with project work and dont have time to start this. If anyone would like to jump in - PRs welcome :D

**Comment by BartusZak** [comment]
Maybe someone will find that usefull

I went with schema validation, but:

- it does not work with `serverless-offline`
- I did not find a way to customize error message. It always says `"Validation Error"` or something like that.

e.g:
`serverless.yml`

```
functions:
  create:
    handler: handlers/create.handler
    events:
      - http:
          path: movies
          method: post
          cors: true
          request:
            schema:
              application/json: ${file(models/movie.json)}
```

`models/movie.json`
```
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Movie",
  "required": ["categories", "description", "title"],
  "properties": {
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "title": "Categories"
    },
    "description": {
      "type": "string",
      "title": "Description"
    },
    "title": {
      "type": "string",
      "title": "Title"
    }
  }
}
```

Looking forward to see better solutions.
