### ISSUE TITLE
Warning: unrecognized property 'reqValidatorName'

### ISSUE THREAD

**Issue by jcandrade** [RafPe/serverless-reqvalidator-plugin#21]
After updating the framework to version 2.19.0, it's throwing this warning on deploy:

```
Serverless: Configuration warning:
Serverless:   at 'functions.XXX.events[0].http': unrecognized property 'reqValidatorName'
```

Here's my plugin serverless.yml:
```
functions:
  XXX:
    handler: src/XXX.xxx
    events:
      - http:
          path: /api/XXX
          method: get
          reqValidatorName: onlyParamsValidator
          request:
            parameters:
              headers:
                'Header-X': true
                
resources:
  Resources:
    onlyParamsValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'Validate query params and headers'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: false
        ValidateRequestParameters: true
 ```

**Comment by RafPe** [comment]
Hi @jcandrade - can you paste the whole of your serverless config ( or at least the parts when you reference required plugins ? )

**Comment by RafPe** [comment]
I really need more details to work here. What is the SLS version installed ?

Please paste the server less.yaml

**Comment by jcandrade** [comment]
@RafPe I shared a short version of my serverless.yml, but here are a few more lines:

Version:
```
➜  ~ sls -v
Framework Core: 2.19.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.5.0
```

serverless.yml
```
service: lambdas

plugins:
  - serverless-plugin-typescript
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

custom:
  customDomain:
    domainName: xxx.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  tracing:
    apiGateway: true
    lambda: true
  logRetentionInDays: 14
  lambdaHashingVersion: 20201221
  apiName: ${opt:stage, self:provider.stage}

package:
  individually: true

functions:
  XXX:
    name: ${self:provider.stage}-get-principal
    handler: src/XXX.xxx
    events:
      - http:
          path: /api/xxx
          method: get
          cors:
            origin: '*'
            headers:
              - '*'
          reqValidatorName: onlyParamsValidator
          request:
            parameters:
              headers:
                'Authorization': true

resources:
  Resources:
    onlyParamsValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'Validate query params and headers'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: false
        ValidateRequestParameters: true

**Comment by RafPe** [comment]
@jcandrade Did not experience any problems you are describing when running the stack 

```
❯ serverless --version
Framework Core: 2.19.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```

I have also strip down a bit of your yaml to deploy on my end 

```
service: test-gh-issue

plugins:
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs12.x
  stage: test
  region: eu-central-1

functions:
  test:
    name: test-xxx
    handler: src/handler.js
    events:
      - http:
          path: /api/xxx
          method: get
          cors:
            origin: '*'
            headers:
              - '*'
          reqValidatorName: onlyParamsValidator

package:
  include:
    - ./src

resources:
  Resources:
    onlyParamsValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'Validate query params and headers'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: false
        ValidateRequestParameters: true
```
