### ISSUE TITLE
reqValidatorName needed for a mock endpoint?

### ISSUE THREAD

**Issue by nbcchen** [RafPe/serverless-reqvalidator-plugin#34]
I got a warning:
> Warning: Invalid configuration encountered
  at 'functions.xxx.events.1.http': must have required property 'reqValidatorName'

endpoint definition:
```yaml
    - http:
        path: healthcheck
        cors: true
        method: get
        integration: mock
        request:
          template:
            application/json: '{"statusCode": 200}'
        response:
          template: '{ "status": "healthy" }'
          statusCodes:
            200:
              pattern: ''
```
I am using it as a healthcheck and it's a [MOCK integration](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-mock-integration.html) and i don't need request validator. How do I turn it off?
